# Generated by Django 4.0.4 on 2022-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image'),
        ),
    ]
